### ISSUE TITLE
Baud unstable 

### ISSUE THREAD

**Issue by BugsonPL** [CobraPi/Klipper-Firmware-FLSUN-QQ-S-Pro#3]
I find the default baud unstable with Flsun highspeed 1.0 board.
Looks like you are having the same problem "Timeout during homing"
115200 works for me fine.

If you could confirm it is worth changing.

**Comment by CobraPi** [comment]
Hmm that's strange. The default baud rate of 250000 works pretty well on my Highspeed board. Others seem to have no issue with it. It's even recommended in the documentation: 

https://www.klipper3d.org/FAQ.html#how-do-i-change-the-serial-baud-rate

Lowering your baud rate may affect the functionality/resolution of Klipper because the Raspberry Pi has to send all the printer instructions via the serial port.

**Comment by BugsonPL** [comment]
With other boards I also use 250000 but with this one it is not stable. I don't see any problems with performance.

**Comment by CobraPi** [comment]
Okay, since only a minority of people have this problem I'll add it to the troubleshooting section of the README.
